# Generated by Django 4.0.2 on 2022-04-16 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0002_station_booked_batteries'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is paid by user')),
                ('is_collected', models.BooleanField(default=False, verbose_name='Is collected by user')),
                ('booked_time', models.DateTimeField(auto_now_add=True, verbose_name='Order booked at')),
                ('expiry_time', models.DateTimeField(verbose_name='Order expires on')),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battery.battery')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battery.station')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='Orders', to='user.Order'),
        ),
    ]
