# Generated by Django 4.0.2 on 2022-04-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_order_user_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, null=True, verbose_name='Phone'),
        ),
    ]
