# Generated by Django 4.0.2 on 2022-04-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=150, null=True, verbose_name='Station Name'),
        ),
    ]
