# Generated by Django 4.0.2 on 2022-04-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='booked_batteries',
            field=models.ManyToManyField(blank=True, related_name='Booked_Batteries', to='battery.Battery'),
        ),
    ]
